name: Update Bitcoin Price

on:  
  schedule:
    - cron: '*/5 * * * *'
    
jobs:
  update:
    environment: secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Run script
        run: node "$(pwd)/update.js"
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'WKoA'
          git config --global user.email 'Reginald-Gillespie@users.noreply.github.com'
          git commit -am "Automated report"
          git push

