name: Update Bitcoin Price

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-price:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.5.3
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: npm install
      - name: Check path
        run: ls && cd .. && ls
      - name: Update Bitcoin Price
        run: node update.js
      - name: Commit Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Update Bitcoin price"
          git push
