name: Update Bitcoin Price

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-price:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install axios
      - name: Update Price
        run: |
          const axios = require("axios");
          const fs = require("fs");

          axios
            .get("https://api.coindesk.com/v1/bpi/currentprice.json")
            .then((response) => {
              const currentPrice = response.data.bpi.USD.rate;

              const filePath = "./path/to/your/javascript/file.js";
              const fileContent = fs.readFileSync(filePath, "utf-8");

              const updatedContent = fileContent.replace(
                /var price = ".*";/,
                `var price = "${currentPrice}";`
              );

              fs.writeFileSync(filePath, updatedContent);
            });
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Bitcoin Price"
          commit_options: "--no-gpg-sign"
